# PANDAS

In [1]:
import pandas as pd

In [5]:
pd.set_option('display.max.rows', 150)

In [55]:
original_df = pd.read_csv(r"C:\Users\fokike\OneDrive\Data Analytics Portfolio\Companies.csv")

original_df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology and cloud computing,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,AmerisourceBergen,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology and cloud computing,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive industry,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate and telecomunications,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Arlington County, Virginia"
60,61,StoneX Group,Financials,"66,036",55.3%,305,"New York City, New York"
61,62,Lockheed Martin,Aerospace and defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology and cloud computing,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom hardware manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [7]:
df[df['Rank']< 10]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology and cloud computing,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"

In [11]:
specific_industries = ['Retail','Healthcare']

df[df['Industry'].isin(specific_industries)]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"

In [12]:
df[df['Name'].str.contains('Energy')]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"

In [13]:
df2 = df.set_index('Industry')
df2

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Retail,1,Walmart,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Retail and cloud computing,2,Amazon,"513,983",9.4%,"1,540,000","Seattle, Washington"
Petroleum industry,3,ExxonMobil,"413,680",44.8%,"62,000","Spring, Texas"
Electronics industry,4,Apple,"394,328",7.8%,"164,000","Cupertino, California"
Healthcare,5,UnitedHealth Group,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
Healthcare,6,CVS Health,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Conglomerate,7,Berkshire Hathaway,"302,089",9.4%,"383,000","Omaha, Nebraska"
Technology and cloud computing,8,Alphabet,"282,836",9.8%,"156,000","Mountain View, California"
Health,9,McKesson Corporation,"276,711",4.8%,"48,500","Irving, Texas"
Petroleum industry,10,Chevron Corporation,"246,252",51.6%,"43,846","San Ramon, California"
Pharmaceutical industry,11,AmerisourceBergen,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Retail,12,Costco,"226,954",15.8%,"304,000","Issaquah, Washington"
Technology and cloud computing,13,Microsoft,"198,270",18.0%,"221,000","Redmond, Washington"
Healthcare,14,Cardinal Health,"181,364",11.6%,"46,035","Dublin, Ohio"
Health insurance,15,Cigna,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Petroleum industry,16,Marathon Petroleum,"180,012",27.6%,"17,800","Findlay, Ohio"
Petroleum industry,17,Phillips 66,"175,702",53.0%,"13,000","Houston, Texas"
Petroleum industry,18,Valero Energy,"171,189",58.0%,"9,743","San Antonio, Texas"
Automotive industry,19,Ford Motor Company,"158,057",15.9%,"173,000","Dearborn, Michigan"
Retail,20,The Home Depot,"157,403",4.1%,"471,600","Atlanta, Georgia"
Automotive industry,21,General Motors,"156,735",23.4%,"167,000","Detroit, Michigan"
Healthcare,22,Elevance Health,"156,595",13.0%,"102,200","Indianapolis, Indiana"
Financial services,23,JPMorgan Chase,"154,792",21.7%,"293,723","New York City, New York"
Retail,24,Kroger,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Healthcare,25,Centene,"144,547",14.7%,"74,300","St. Louis, Missouri"
Telecommunications,26,Verizon Communications,"136,835",2.4%,"117,100","New York City, New York"
Pharmaceutical industry,27,Walgreens Boots Alliance,"132,703",10.7%,"262,500","Deerfield, Illinois"
Financials,28,Fannie Mae,"121,596",19.7%,"8,000","Washington, D.C."
Telecommunications,29,Comcast,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
Conglomerate and telecomunications,30,AT&T,"120,741",28.5%,"160,700","Dallas, Texas"
Technology,31,Meta Platforms,"116,609",1.1%,"86,482","Menlo Park, California"
Financials,32,Bank of America,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Retail,33,Target Corporation,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Technology,34,Dell Technologies,"102,301",4.4%,"133,000","Round Rock, Texas"
Food industry,35,Archer Daniels Midland,"101,556",19.1%,"41,181","Chicago, Illinois"
Financials,36,Citigroup,"101,078",26.6%,"238,104","New York City, New York"
Transportation,37,United Parcel Service,"100,338",3.1%,"404,700","Atlanta, Georgia"
Pharmaceutical industry,38,Pfizer,"100,330",23.4%,"83,000","New York City, New York"
Retail,39,Lowe's,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Pharmaceutical industry,40,Johnson & Johnson,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
Transportation,41,FedEx,"93,512",11.4%,"518,249","Memphis, Tennessee"
Health insurance,42,Humana,"92,870",11.8%,"67,100","Louisville, Kentucky"
Petroleum industry,43,Energy Transfer Partners,"89,876",33.3%,"12,565","Dallas, Texas"
Financials,44,State Farm,"89,328",8.6%,"60,519","Bloomington, Illinois"
Financials,45,Freddie Mac,"86,717",31.6%,"7,819","McLean, Virginia"
Beverage,46,PepsiCo,"86,859",8.7%,"315,000","Purchase, New York"
Financials,47,Wells Fargo,"82,859",0.5%,"238,000","San Francisco, California"
Media,48,The Walt Disney Company,"82,722",22.7%,"195,800","Burbank, California"
Petroleum industry,49,ConocoPhillips,"82,156",69.9%,"9,500","Houston, Texas"
Automotive and energy,50,Tesla,"81,462",51.4%,"127,855","Austin, Texas"
Consumer products manufacturing,51,Procter & Gamble,"80,187",5.3%,"106,000","Cincinnati, Ohio"
Logistics,52,United States Postal Service,"78,620",2.0%,"576,000","Washington, D.C."
Retail,53,Albertsons,"77,650",8.0%,"198,650","Boise, Idaho"
Conglomerate,54,General Electric,"76,555",3.2%,"172,000","Boston, Massachusetts"
Financials,55,MetLife,"69,898",1.7%,"45,000","New York City, New York"
Financials,56,Goldman Sachs,"68,711",5.7%,"48,500","New York City, New York"
Food service,57,Sysco,"68,636",33.8%,"70,510","Houston, Texas"
Food industry,58,Bunge Limited,"67,232",13.7%,"23,000","White Plains, New York"
Conglomerate,59,RTX Corporation,"67,074",4.2%,"182,000","Arlington County, Virginia"
Aerospace and defense,60,Boeing,"66,608",6.9%,"156,000","Arlington County, Virginia"
Financials,61,StoneX Group,"66,036",55.3%,305,"New York City, New York"
Aerospace and defense,62,Lockheed Martin,"65,984",1.6%,"116,000","Bethesda, Maryland"
Financials,63,Morgan Stanley,"65,936",7.9%,"82,427","New York City, New York"
Technology,64,Intel,"63,054",20.1%,"131,900","Santa Clara, California"
Technology,65,HP,"62,983",0.8%,"58,000","Palo Alto, California"
Infotech,66,TD Synnex,"62,344",97.2%,"28,500","Clearwater, Florida"
Technology and cloud computing,67,IBM,"60,530",16.3%,"303,100","Armonk, New York"
Healthcare,68,HCA Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
Financials,69,Prudential Financial,"60,050",15.3%,"39,583","Newark, New Jersey"
Machinery,70,Caterpillar,"59,427",16.6%,"109,100","Deerfield, Illinois"
Pharmaceutical industry,71,Merck & Co.,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
Petroleum industry and logistics,72,World Fuel Services,"59,043",88.4%,"5,214","Miami, Florida"
Insurance,73,New York Life Insurance Company,"58,445",14.2%,"15,050","New York City, New York"
Petroleum industry,74,Enterprise Products,"58,186",42.6%,"7,300","Houston, Texas"
Pharmaceutical industry,75,AbbVie,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Petroleum industry,76,Plains All American Pipeline,"57,342",36.3%,"4,100","Houston, Texas"
Chemical industry,77,Dow Chemical Company,"56,902",3.5%,"37,800","Midland, Michigan"
Insurance,78,AIG,"56,437",8.4%,"26,200","New York City, New York"
Financial,79,American Express,"55,625",27.3%,"77,300","New York City, New York"
Retail,80,Publix,"54,942",13.5%,"242,000","Lakeland, Florida"
Telecommunications,81,Charter Communications,"54,022",4.5%,"101,700","Stamford, Connecticut"
Food processing,82,Tyson Foods,"53,282",13.2%,"142,000","Springdale, Arkansas"
Agriculture manufacturing,83,John Deere,"52,577",19.4%,"82,239","Moline, Illinois"
Telecom hardware manufacturing,84,Cisco,"51,557",3.5%,"83,300","San Jose, California"
Financial,85,Nationwide Mutual Insurance Company,"51,450",8.6%,"24,791","Columbus, Ohio"
Insurance,86,Allstate,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Airline,87,Delta Air Lines,"50,582",69.2%,"95,000","Atlanta, Georgia"
Insurance,88,Liberty Mutual,"49,956",3.6%,"50,000","Boston, Massachusetts"
Retail,89,TJX,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Insurance,90,Progressive Corporation,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
Airline,91,American Airlines,"48,971",63.9%,"129,700","Fort Worth, Texas"
Agriculture cooperative,92,CHS,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Food processing,93,Performance Food Group,"47,194",61.6%,"34,825","Richmond, Virginia"
Petroleum industry,94,PBF Energy,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
Apparel,95,Nike,"46,710",4.9%,"79,100","Beaverton, Oregon"
Retail,96,Best Buy,"46,298",10.6%,"71,100","Richfield, Minnesota"
Pharmaceutical industry,97,Bristol-Myers Squibb,"46,159",0.5%,"34,300","New York City, New York"
Airline,98,United Airlines,"44,955",82.5%,"92,795","Chicago, Illinois"
Laboratory instruments,99,Thermo Fisher Scientific,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Technology,100,Qualcomm,"44,200",31.7%,"51,000","San Diego, California"

In [14]:
df2.filter(items = ['Name','Headquarters'])

,Name,Headquarters
Industry,,
Retail,Walmart,"Bentonville, Arkansas"
Retail and cloud computing,Amazon,"Seattle, Washington"
Petroleum industry,ExxonMobil,"Spring, Texas"
Electronics industry,Apple,"Cupertino, California"
Healthcare,UnitedHealth Group,"Minnetonka, Minnesota"
Healthcare,CVS Health,"Woonsocket, Rhode Island"
Conglomerate,Berkshire Hathaway,"Omaha, Nebraska"
Technology and cloud computing,Alphabet,"Mountain View, California"
Health,McKesson Corporation,"Irving, Texas"
Petroleum industry,Chevron Corporation,"San Ramon, California"
Pharmaceutical industry,AmerisourceBergen,"Chesterbrook, Pennsylvania"
Retail,Costco,"Issaquah, Washington"
Technology and cloud computing,Microsoft,"Redmond, Washington"
Healthcare,Cardinal Health,"Dublin, Ohio"
Health insurance,Cigna,"Bloomfield, Connecticut"
Petroleum industry,Marathon Petroleum,"Findlay, Ohio"
Petroleum industry,Phillips 66,"Houston, Texas"
Petroleum industry,Valero Energy,"San Antonio, Texas"
Automotive industry,Ford Motor Company,"Dearborn, Michigan"
Retail,The Home Depot,"Atlanta, Georgia"
Automotive industry,General Motors,"Detroit, Michigan"
Healthcare,Elevance Health,"Indianapolis, Indiana"
Financial services,JPMorgan Chase,"New York City, New York"
Retail,Kroger,"Cincinnati, Ohio"
Healthcare,Centene,"St. Louis, Missouri"
Telecommunications,Verizon Communications,"New York City, New York"
Pharmaceutical industry,Walgreens Boots Alliance,"Deerfield, Illinois"
Financials,Fannie Mae,"Washington, D.C."
Telecommunications,Comcast,"Philadelphia, Pennsylvania"
Conglomerate and telecomunications,AT&T,"Dallas, Texas"
Technology,Meta Platforms,"Menlo Park, California"
Financials,Bank of America,"Charlotte, North Carolina"
Retail,Target Corporation,"Minneapolis, Minnesota"
Technology,Dell Technologies,"Round Rock, Texas"
Food industry,Archer Daniels Midland,"Chicago, Illinois"
Financials,Citigroup,"New York City, New York"
Transportation,United Parcel Service,"Atlanta, Georgia"
Pharmaceutical industry,Pfizer,"New York City, New York"
Retail,Lowe's,"Mooresville, North Carolina"
Pharmaceutical industry,Johnson & Johnson,"New Brunswick, New Jersey"
Transportation,FedEx,"Memphis, Tennessee"
Health insurance,Humana,"Louisville, Kentucky"
Petroleum industry,Energy Transfer Partners,"Dallas, Texas"
Financials,State Farm,"Bloomington, Illinois"
Financials,Freddie Mac,"McLean, Virginia"
Beverage,PepsiCo,"Purchase, New York"
Financials,Wells Fargo,"San Francisco, California"
Media,The Walt Disney Company,"Burbank, California"
Petroleum industry,ConocoPhillips,"Houston, Texas"
Automotive and energy,Tesla,"Austin, Texas"
Consumer products manufacturing,Procter & Gamble,"Cincinnati, Ohio"
Logistics,United States Postal Service,"Washington, D.C."
Retail,Albertsons,"Boise, Idaho"
Conglomerate,General Electric,"Boston, Massachusetts"
Financials,MetLife,"New York City, New York"
Financials,Goldman Sachs,"New York City, New York"
Food service,Sysco,"Houston, Texas"
Food industry,Bunge Limited,"White Plains, New York"
Conglomerate,RTX Corporation,"Arlington County, Virginia"
Aerospace and defense,Boeing,"Arlington County, Virginia"
Financials,StoneX Group,"New York City, New York"
Aerospace and defense,Lockheed Martin,"Bethesda, Maryland"
Financials,Morgan Stanley,"New York City, New York"
Technology,Intel,"Santa Clara, California"
Technology,HP,"Palo Alto, California"
Infotech,TD Synnex,"Clearwater, Florida"
Technology and cloud computing,IBM,"Armonk, New York"
Healthcare,HCA Healthcare,"Nashville, Tennessee"
Financials,Prudential Financial,"Newark, New Jersey"
Machinery,Caterpillar,"Deerfield, Illinois"
Pharmaceutical industry,Merck & Co.,"Kenilworth, New Jersey"
Petroleum industry and logistics,World Fuel Services,"Miami, Florida"
Insurance,New York Life Insurance Company,"New York City, New York"
Petroleum industry,Enterprise Products,"Houston, Texas"
Pharmaceutical industry,AbbVie,"Lake Bluff, Illinois"
Petroleum industry,Plains All American Pipeline,"Houston, Texas"
Chemical industry,Dow Chemical Company,"Midland, Michigan"
Insurance,AIG,"New York City, New York"
Financial,American Express,"New York City, New York"
Retail,Publix,"Lakeland, Florida"
Telecommunications,Charter Communications,"Stamford, Connecticut"
Food processing,Tyson Foods,"Springdale, Arkansas"
Agriculture manufacturing,John Deere,"Moline, Illinois"
Telecom hardware manufacturing,Cisco,"San Jose, California"
Financial,Nationwide Mutual Insurance Company,"Columbus, Ohio"
Insurance,Allstate,"Northfield Township, Cook County, Illinois"
Airline,Delta Air Lines,"Atlanta, Georgia"
Insurance,Liberty Mutual,"Boston, Massachusetts"
Retail,TJX,"Framingham, Massachusetts"
Insurance,Progressive Corporation,"Mayfield Village, Ohio"
Airline,American Airlines,"Fort Worth, Texas"
Agriculture cooperative,CHS,"Inver Grove Heights, Minnesota"
Food processing,Performance Food Group,"Richmond, Virginia"
Petroleum industry,PBF Energy,"Parsippany–Troy Hills, New Jersey"
Apparel,Nike,"Beaverton, Oregon"
Retail,Best Buy,"Richfield, Minnesota"
Pharmaceutical industry,Bristol-Myers Squibb,"New York City, New York"
Airline,United Airlines,"Chicago, Illinois"
Laboratory instruments,Thermo Fisher Scientific,"Waltham, Massachusetts"
Technology,Qualcomm,"San Diego, California"

In [20]:
df2[df2['Rank'] > 40].sort_values(by=['Industry','Name'], ascending = [True, False])

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Aerospace and defense,62,Lockheed Martin,"65,984",1.6%,"116,000","Bethesda, Maryland"
Aerospace and defense,60,Boeing,"66,608",6.9%,"156,000","Arlington County, Virginia"
Agriculture cooperative,92,CHS,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Agriculture manufacturing,83,John Deere,"52,577",19.4%,"82,239","Moline, Illinois"
Airline,98,United Airlines,"44,955",82.5%,"92,795","Chicago, Illinois"
Airline,87,Delta Air Lines,"50,582",69.2%,"95,000","Atlanta, Georgia"
Airline,91,American Airlines,"48,971",63.9%,"129,700","Fort Worth, Texas"
Apparel,95,Nike,"46,710",4.9%,"79,100","Beaverton, Oregon"
Automotive and energy,50,Tesla,"81,462",51.4%,"127,855","Austin, Texas"
Beverage,46,PepsiCo,"86,859",8.7%,"315,000","Purchase, New York"
Chemical industry,77,Dow Chemical Company,"56,902",3.5%,"37,800","Midland, Michigan"
Conglomerate,59,RTX Corporation,"67,074",4.2%,"182,000","Arlington County, Virginia"
Conglomerate,54,General Electric,"76,555",3.2%,"172,000","Boston, Massachusetts"
Consumer products manufacturing,51,Procter & Gamble,"80,187",5.3%,"106,000","Cincinnati, Ohio"
Financial,85,Nationwide Mutual Insurance Company,"51,450",8.6%,"24,791","Columbus, Ohio"
Financial,79,American Express,"55,625",27.3%,"77,300","New York City, New York"
Financials,47,Wells Fargo,"82,859",0.5%,"238,000","San Francisco, California"
Financials,61,StoneX Group,"66,036",55.3%,305,"New York City, New York"
Financials,44,State Farm,"89,328",8.6%,"60,519","Bloomington, Illinois"
Financials,69,Prudential Financial,"60,050",15.3%,"39,583","Newark, New Jersey"
Financials,63,Morgan Stanley,"65,936",7.9%,"82,427","New York City, New York"
Financials,55,MetLife,"69,898",1.7%,"45,000","New York City, New York"
Financials,56,Goldman Sachs,"68,711",5.7%,"48,500","New York City, New York"
Financials,45,Freddie Mac,"86,717",31.6%,"7,819","McLean, Virginia"
Food industry,58,Bunge Limited,"67,232",13.7%,"23,000","White Plains, New York"
Food processing,82,Tyson Foods,"53,282",13.2%,"142,000","Springdale, Arkansas"
Food processing,93,Performance Food Group,"47,194",61.6%,"34,825","Richmond, Virginia"
Food service,57,Sysco,"68,636",33.8%,"70,510","Houston, Texas"
Health insurance,42,Humana,"92,870",11.8%,"67,100","Louisville, Kentucky"
Healthcare,68,HCA Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
Infotech,66,TD Synnex,"62,344",97.2%,"28,500","Clearwater, Florida"
Insurance,90,Progressive Corporation,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
Insurance,73,New York Life Insurance Company,"58,445",14.2%,"15,050","New York City, New York"
Insurance,88,Liberty Mutual,"49,956",3.6%,"50,000","Boston, Massachusetts"
Insurance,86,Allstate,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Insurance,78,AIG,"56,437",8.4%,"26,200","New York City, New York"
Laboratory instruments,99,Thermo Fisher Scientific,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Logistics,52,United States Postal Service,"78,620",2.0%,"576,000","Washington, D.C."
Machinery,70,Caterpillar,"59,427",16.6%,"109,100","Deerfield, Illinois"
Media,48,The Walt Disney Company,"82,722",22.7%,"195,800","Burbank, California"
Petroleum industry,76,Plains All American Pipeline,"57,342",36.3%,"4,100","Houston, Texas"
Petroleum industry,94,PBF Energy,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
Petroleum industry,74,Enterprise Products,"58,186",42.6%,"7,300","Houston, Texas"
Petroleum industry,43,Energy Transfer Partners,"89,876",33.3%,"12,565","Dallas, Texas"
Petroleum industry,49,ConocoPhillips,"82,156",69.9%,"9,500","Houston, Texas"
Petroleum industry and logistics,72,World Fuel Services,"59,043",88.4%,"5,214","Miami, Florida"
Pharmaceutical industry,71,Merck & Co.,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
Pharmaceutical industry,97,Bristol-Myers Squibb,"46,159",0.5%,"34,300","New York City, New York"
Pharmaceutical industry,75,AbbVie,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Retail,89,TJX,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Retail,80,Publix,"54,942",13.5%,"242,000","Lakeland, Florida"
Retail,96,Best Buy,"46,298",10.6%,"71,100","Richfield, Minnesota"
Retail,53,Albertsons,"77,650",8.0%,"198,650","Boise, Idaho"
Technology,100,Qualcomm,"44,200",31.7%,"51,000","San Diego, California"
Technology,64,Intel,"63,054",20.1%,"131,900","Santa Clara, California"
Technology,65,HP,"62,983",0.8%,"58,000","Palo Alto, California"
Technology and cloud computing,67,IBM,"60,530",16.3%,"303,100","Armonk, New York"
Telecom hardware manufacturing,84,Cisco,"51,557",3.5%,"83,300","San Jose, California"
Telecommunications,81,Charter Communications,"54,022",4.5%,"101,700","Stamford, Connecticut"
Transportation,41,FedEx,"93,512",11.4%,"518,249","Memphis, Tennessee"

In [23]:
df2.loc['Retail']

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Retail,1,Walmart,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Retail,12,Costco,"226,954",15.8%,"304,000","Issaquah, Washington"
Retail,20,The Home Depot,"157,403",4.1%,"471,600","Atlanta, Georgia"
Retail,24,Kroger,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Retail,33,Target Corporation,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Retail,39,Lowe's,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Retail,53,Albertsons,"77,650",8.0%,"198,650","Boise, Idaho"
Retail,80,Publix,"54,942",13.5%,"242,000","Lakeland, Florida"
Retail,89,TJX,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Retail,96,Best Buy,"46,298",10.6%,"71,100","Richfield, Minnesota"

In [27]:
df2.iloc[6]

Rank                                       7
Name                      Berkshire Hathaway
Revenue (USD millions)               302,089
Revenue growth                          9.4%
Employees                            383,000
Headquarters                 Omaha, Nebraska
Name: Conglomerate, dtype: object

In [28]:
df2.reset_index(inplace = True)

In [29]:
df2

,Industry,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,Retail,1,Walmart,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,Retail and cloud computing,2,Amazon,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,Petroleum industry,3,ExxonMobil,"413,680",44.8%,"62,000","Spring, Texas"
3,Electronics industry,4,Apple,"394,328",7.8%,"164,000","Cupertino, California"
4,Healthcare,5,UnitedHealth Group,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,Healthcare,6,CVS Health,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,Conglomerate,7,Berkshire Hathaway,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,Technology and cloud computing,8,Alphabet,"282,836",9.8%,"156,000","Mountain View, California"
8,Health,9,McKesson Corporation,"276,711",4.8%,"48,500","Irving, Texas"
9,Petroleum industry,10,Chevron Corporation,"246,252",51.6%,"43,846","San Ramon, California"
10,Pharmaceutical industry,11,AmerisourceBergen,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,Retail,12,Costco,"226,954",15.8%,"304,000","Issaquah, Washington"
12,Technology and cloud computing,13,Microsoft,"198,270",18.0%,"221,000","Redmond, Washington"
13,Healthcare,14,Cardinal Health,"181,364",11.6%,"46,035","Dublin, Ohio"
14,Health insurance,15,Cigna,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,Petroleum industry,16,Marathon Petroleum,"180,012",27.6%,"17,800","Findlay, Ohio"
16,Petroleum industry,17,Phillips 66,"175,702",53.0%,"13,000","Houston, Texas"
17,Petroleum industry,18,Valero Energy,"171,189",58.0%,"9,743","San Antonio, Texas"
18,Automotive industry,19,Ford Motor Company,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,Retail,20,The Home Depot,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,Automotive industry,21,General Motors,"156,735",23.4%,"167,000","Detroit, Michigan"
21,Healthcare,22,Elevance Health,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,Financial services,23,JPMorgan Chase,"154,792",21.7%,"293,723","New York City, New York"
23,Retail,24,Kroger,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,Healthcare,25,Centene,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,Telecommunications,26,Verizon Communications,"136,835",2.4%,"117,100","New York City, New York"
26,Pharmaceutical industry,27,Walgreens Boots Alliance,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,Financials,28,Fannie Mae,"121,596",19.7%,"8,000","Washington, D.C."
28,Telecommunications,29,Comcast,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,Conglomerate and telecomunications,30,AT&T,"120,741",28.5%,"160,700","Dallas, Texas"
30,Technology,31,Meta Platforms,"116,609",1.1%,"86,482","Menlo Park, California"
31,Financials,32,Bank of America,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,Retail,33,Target Corporation,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,Technology,34,Dell Technologies,"102,301",4.4%,"133,000","Round Rock, Texas"
34,Food industry,35,Archer Daniels Midland,"101,556",19.1%,"41,181","Chicago, Illinois"
35,Financials,36,Citigroup,"101,078",26.6%,"238,104","New York City, New York"
36,Transportation,37,United Parcel Service,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,Pharmaceutical industry,38,Pfizer,"100,330",23.4%,"83,000","New York City, New York"
38,Retail,39,Lowe's,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,Pharmaceutical industry,40,Johnson & Johnson,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,Transportation,41,FedEx,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,Health insurance,42,Humana,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,Petroleum industry,43,Energy Transfer Partners,"89,876",33.3%,"12,565","Dallas, Texas"
43,Financials,44,State Farm,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,Financials,45,Freddie Mac,"86,717",31.6%,"7,819","McLean, Virginia"
45,Beverage,46,PepsiCo,"86,859",8.7%,"315,000","Purchase, New York"
46,Financials,47,Wells Fargo,"82,859",0.5%,"238,000","San Francisco, California"
47,Media,48,The Walt Disney Company,"82,722",22.7%,"195,800","Burbank, California"
48,Petroleum industry,49,ConocoPhillips,"82,156",69.9%,"9,500","Houston, Texas"
49,Automotive and energy,50,Tesla,"81,462",51.4%,"127,855","Austin, Texas"
50,Consumer products manufacturing,51,Procter & Gamble,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,Logistics,52,United States Postal Service,"78,620",2.0%,"576,000","Washington, D.C."
52,Retail,53,Albertsons,"77,650",8.0%,"198,650","Boise, Idaho"
53,Conglomerate,54,General Electric,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,Financials,55,MetLife,"69,898",1.7%,"45,000","New York City, New York"
55,Financials,56,Goldman Sachs,"68,711",5.7%,"48,500","New York City, New York"
56,Food service,57,Sysco,"68,636",33.8%,"70,510","Houston, Texas"
57,Food industry,58,Bunge Limited,"67,232",13.7%,"23,000","White Plains, New York"
58,Conglomerate,59,RTX Corporation,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,Aerospace and defense,60,Boeing,"66,608",6.9%,"156,000","Arlington County, Virginia"
60,Financials,61,StoneX Group,"66,036",55.3%,305,"New York City, New York"
61,Aerospace and defense,62,Lockheed Martin,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,Financials,63,Morgan Stanley,"65,936",7.9%,"82,427","New York City, New York"
63,Technology,64,Intel,"63,054",20.1%,"131,900","Santa Clara, California"
64,Technology,65,HP,"62,983",0.8%,"58,000","Palo Alto, California"
65,Infotech,66,TD Synnex,"62,344",97.2%,"28,500","Clearwater, Florida"
66,Technology and cloud computing,67,IBM,"60,530",16.3%,"303,100","Armonk, New York"
67,Healthcare,68,HCA Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,Financials,69,Prudential Financial,"60,050",15.3%,"39,583","Newark, New Jersey"
69,Machinery,70,Caterpillar,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,Pharmaceutical industry,71,Merck & Co.,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,Petroleum industry and logistics,72,World Fuel Services,"59,043",88.4%,"5,214","Miami, Florida"
72,Insurance,73,New York Life Insurance Company,"58,445",14.2%,"15,050","New York City, New York"
73,Petroleum industry,74,Enterprise Products,"58,186",42.6%,"7,300","Houston, Texas"
74,Pharmaceutical industry,75,AbbVie,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,Petroleum industry,76,Plains All American Pipeline,"57,342",36.3%,"4,100","Houston, Texas"
76,Chemical industry,77,Dow Chemical Company,"56,902",3.5%,"37,800","Midland, Michigan"
77,Insurance,78,AIG,"56,437",8.4%,"26,200","New York City, New York"
78,Financial,79,American Express,"55,625",27.3%,"77,300","New York City, New York"
79,Retail,80,Publix,"54,942",13.5%,"242,000","Lakeland, Florida"
80,Telecommunications,81,Charter Communications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,Food processing,82,Tyson Foods,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,Agriculture manufacturing,83,John Deere,"52,577",19.4%,"82,239","Moline, Illinois"
83,Telecom hardware manufacturing,84,Cisco,"51,557",3.5%,"83,300","San Jose, California"
84,Financial,85,Nationwide Mutual Insurance Company,"51,450",8.6%,"24,791","Columbus, Ohio"
85,Insurance,86,Allstate,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,Airline,87,Delta Air Lines,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,Insurance,88,Liberty Mutual,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,Retail,89,TJX,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,Insurance,90,Progressive Corporation,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,Airline,91,American Airlines,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,Agriculture cooperative,92,CHS,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,Food processing,93,Performance Food Group,"47,194",61.6%,"34,825","Richmond, Virginia"
93,Petroleum industry,94,PBF Energy,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
94,Apparel,95,Nike,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,Retail,96,Best Buy,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,Pharmaceutical industry,97,Bristol-Myers Squibb,"46,159",0.5%,"34,300","New York City, New York"
97,Airline,98,United Airlines,"44,955",82.5%,"92,795","Chicago, Illinois"
98,Laboratory instruments,99,Thermo Fisher Scientific,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,Technology,100,Qualcomm,"44,200",31.7%,"51,000","San Diego, California"

In [32]:
df2.set_index(['Industry','Name'], inplace =True)

In [33]:
df2

                                                                        Rank  \
Industry                           Name
Retail                             Walmart                                 1
Retail and cloud computing         Amazon                                  2
Petroleum industry                 ExxonMobil                              3
Electronics industry               Apple                                   4
Healthcare                         UnitedHealth Group                      5
                                   CVS Health                              6
Conglomerate                       Berkshire Hathaway                      7
Technology and cloud computing     Alphabet                                8
Health                             McKesson Corporation                    9
Petroleum industry                 Chevron Corporation                    10
Pharmaceutical industry            AmerisourceBergen                      11
Retail                             Costco                                 12
Technology and cloud computing     Microsoft                              13
Healthcare                         Cardinal Health                        14
Health insurance                   Cigna                                  15
Petroleum industry                 Marathon Petroleum                     16
                                   Phillips 66                            17
                                   Valero Energy                          18
Automotive industry                Ford Motor Company                     19
Retail                             The Home Depot                         20
Automotive industry                General Motors                         21
Healthcare                         Elevance Health                        22
Financial services                 JPMorgan Chase                         23
Retail                             Kroger                                 24
Healthcare                         Centene                                25
Telecommunications                 Verizon Communications                 26
Pharmaceutical industry            Walgreens Boots Alliance               27
Financials                         Fannie Mae                             28
Telecommunications                 Comcast                                29
Conglomerate and telecomunications AT&T                                   30
Technology                         Meta Platforms                         31
Financials                         Bank of America                        32
Retail                             Target Corporation                     33
Technology                         Dell Technologies                      34
Food industry                      Archer Daniels Midland                 35
Financials                         Citigroup                              36
Transportation                     United Parcel Service                  37
Pharmaceutical industry            Pfizer                                 38
Retail                             Lowe's                                 39
Pharmaceutical industry            Johnson & Johnson                      40
Transportation                     FedEx                                  41
Health insurance                   Humana                                 42
Petroleum industry                 Energy Transfer Partners               43
Financials                         State Farm                             44
                                   Freddie Mac                            45
Beverage                           PepsiCo                                46
Financials                         Wells Fargo                            47
Media                              The Walt Disney Company                48
Petroleum industry                 ConocoPhillips                         49
Automotive and energy              Tesla                                  50
Consumer products manufacturing    Procter & Gamble                       51
Logistics                          United States Postal Service           52
Retail                             Albertsons                             53
Conglomerate                       General Electric                       54
Financials                         MetLife                                55
                                   Goldman Sachs                          56
Food service                       Sysco                                  57
Food industry                      Bunge Limited                          58
Conglomerate                       RTX Corporation                        59
Aerospace and defense              Boeing                                 60
Financials                         StoneX Group                           61
Aerospace and defense              Lockheed Martin                        62
Financials                         Morgan Stanley                         63
Technology                         Intel                                  64
                                   HP                                     65
Infotech                           TD Synnex                              66
Technology and cloud computing     IBM                                    67
Healthcare                         HCA Healthcare                         68
Financials                         Prudential Financial                   69
Machinery                          Caterpillar                            70
Pharmaceutical industry            Merck & Co.                            71
Petroleum industry and logistics   World Fuel Services                    72
Insurance                          New York Life Insurance Company        73
Petroleum industry                 Enterprise Products                    74
Pharmaceutical industry            AbbVie                                 75
Petroleum industry                 Plains All American Pipeline           76
Chemical industry                  Dow Chemical Company                   77
Insurance                          AIG                                    78
Financial                          American Express                       79
Retail                             Publix                                 80
Telecommunications                 Charter Communications                 81
Food processing                    Tyson Foods                            82
Agriculture manufacturing          John Deere                             83
Telecom hardware manufacturing     Cisco                                  84
Financial                          Nationwide Mutual Insurance Company    85
Insurance                          Allstate                               86
Airline                            Delta Air Lines                        87
Insurance                          Liberty Mutual                         88
Retail                             TJX                                    89
Insurance                          Progressive Corporation                90
Airline                            American Airlines                      91
Agriculture cooperative            CHS                                    92
Food processing                    Performance Food Group                 93
Petroleum industry                 PBF Energy                             94
Apparel                            Nike                                   95
Retail                             Best Buy                               96
Pharmaceutical industry            Bristol-Myers Squibb                   97
Airline                            United Airlines                        98
Laboratory instruments             Thermo Fisher Scientific               99
Technology                         Qualcomm                              100

                                                                       Revenue (USD millions)  \
Industry                           Name
Retail                             Walmart                                            611,289
Retail and cloud computing         Amazon                                             513,983
Petroleum industry                 ExxonMobil                                         413,680
Electronics industry               Apple                                              394,328
Healthcare                         UnitedHealth Group                                 324,162
                                   CVS Health                                         322,467
Conglomerate                       Berkshire Hathaway                                 302,089
Technology and cloud computing     Alphabet                                           282,836
Health                             McKesson Corporation                               276,711
Petroleum industry                 Chevron Corporation                                246,252
Pharmaceutical industry            AmerisourceBergen                                  238,587
Retail                             Costco                                             226,954
Technology and cloud computing     Microsoft                                          198,270
Healthcare                         Cardinal Health                                    181,364
Health insurance                   Cigna                                              180,516
Petroleum industry                 Marathon Petroleum                                 180,012
                                   Phillips 66                                        175,702
                                   Valero Energy                                      171,189
Automotive industry                Ford Motor Company                                 158,057
Retail                             The Home Depot                                     157,403
Automotive industry                General Motors                                     156,735
Healthcare                         Elevance Health                                    156,595
Financial services                 JPMorgan Chase                                     154,792
Retail                             Kroger                                             148,258
Healthcare                         Centene                                            144,547
Telecommunications                 Verizon Communications                             136,835
Pharmaceutical industry            Walgreens Boots Alliance                           132,703
Financials                         Fannie Mae                                         121,596
Telecommunications                 Comcast                                            121,427
Conglomerate and telecomunications AT&T                                               120,741
Technology                         Meta Platforms                                     116,609
Financials                         Bank of America                                    115,053
Retail                             Target Corporation                                 109,120
Technology                         Dell Technologies                                  102,301
Food industry                      Archer Daniels Midland                             101,556
Financials                         Citigroup                                          101,078
Transportation                     United Parcel Service                              100,338
Pharmaceutical industry            Pfizer                                             100,330
Retail                             Lowe's                                              97,059
Pharmaceutical industry            Johnson & Johnson                                   94,943
Transportation                     FedEx                                               93,512
Health insurance                   Humana                                              92,870
Petroleum industry                 Energy Transfer Partners                            89,876
Financials                         State Farm                                          89,328
                                   Freddie Mac                                         86,717
Beverage                           PepsiCo                                             86,859
Financials                         Wells Fargo                                         82,859
Media                              The Walt Disney Company                             82,722
Petroleum industry                 ConocoPhillips                                      82,156
Automotive and energy              Tesla                                               81,462
Consumer products manufacturing    Procter & Gamble                                    80,187
Logistics                          United States Postal Service                        78,620
Retail                             Albertsons                                          77,650
Conglomerate                       General Electric                                    76,555
Financials                         MetLife                                             69,898
                                   Goldman Sachs                                       68,711
Food service                       Sysco                                               68,636
Food industry                      Bunge Limited                                       67,232
Conglomerate                       RTX Corporation                                     67,074
Aerospace and defense              Boeing                                              66,608
Financials                         StoneX Group                                        66,036
Aerospace and defense              Lockheed Martin                                     65,984
Financials                         Morgan Stanley                                      65,936
Technology                         Intel                                               63,054
                                   HP                                                  62,983
Infotech                           TD Synnex                                           62,344
Technology and cloud computing     IBM                                                 60,530
Healthcare                         HCA Healthcare                                      60,233
Financials                         Prudential Financial                                60,050
Machinery                          Caterpillar                                         59,427
Pharmaceutical industry            Merck & Co.                                         59,283
Petroleum industry and logistics   World Fuel Services                                 59,043
Insurance                          New York Life Insurance Company                     58,445
Petroleum industry                 Enterprise Products                                 58,186
Pharmaceutical industry            AbbVie                                              58,054
Petroleum industry                 Plains All American Pipeline                        57,342
Chemical industry                  Dow Chemical Company                                56,902
Insurance                          AIG                                                 56,437
Financial                          American Express                                    55,625
Retail                             Publix                                              54,942
Telecommunications                 Charter Communications                              54,022
Food processing                    Tyson Foods                                         53,282
Agriculture manufacturing          John Deere                                          52,577
Telecom hardware manufacturing     Cisco                                               51,557
Financial                          Nationwide Mutual Insurance Company                 51,450
Insurance                          Allstate                                            51,412
Airline                            Delta Air Lines                                     50,582
Insurance                          Liberty Mutual                                      49,956
Retail                             TJX                                                 49,936
Insurance                          Progressive Corporation                             49,611
Airline                            American Airlines                                   48,971
Agriculture cooperative            CHS                                                 47,194
Food processing                    Performance Food Group                              47,194
Petroleum industry                 PBF Energy                                          46,830
Apparel                            Nike                                                46,710
Retail                             Best Buy                                            46,298
Pharmaceutical industry            Bristol-Myers Squibb                                46,159
Airline                            United Airlines                                     44,955
Laboratory instruments             Thermo Fisher Scientific                            44,915
Technology                         Qualcomm                                            44,200

                                                                       Revenue growth  \
Industry                           Name
Retail                             Walmart                                       6.7%
Retail and cloud computing         Amazon                                        9.4%
Petroleum industry                 ExxonMobil                                   44.8%
Electronics industry               Apple                                         7.8%
Healthcare                         UnitedHealth Group                           12.7%
                                   CVS Health                                   10.4%
Conglomerate                       Berkshire Hathaway                            9.4%
Technology and cloud computing     Alphabet                                      9.8%
Health                             McKesson Corporation                          4.8%
Petroleum industry                 Chevron Corporation                          51.6%
Pharmaceutical industry            AmerisourceBergen                            11.5%
Retail                             Costco                                       15.8%
Technology and cloud computing     Microsoft                                    18.0%
Healthcare                         Cardinal Health                              11.6%
Health insurance                   Cigna                                         3.7%
Petroleum industry                 Marathon Petroleum                           27.6%
                                   Phillips 66                                  53.0%
                                   Valero Energy                                58.0%
Automotive industry                Ford Motor Company                           15.9%
Retail                             The Home Depot                                4.1%
Automotive industry                General Motors                               23.4%
Healthcare                         Elevance Health                              13.0%
Financial services                 JPMorgan Chase                               21.7%
Retail                             Kroger                                        7.5%
Healthcare                         Centene                                      14.7%
Telecommunications                 Verizon Communications                        2.4%
Pharmaceutical industry            Walgreens Boots Alliance                     10.7%
Financials                         Fannie Mae                                   19.7%
Telecommunications                 Comcast                                       4.3%

In [34]:
df2.sort_index()

                                                                        Rank  \
Industry                           Name
Aerospace and defense              Boeing                                 60
                                   Lockheed Martin                        62
Agriculture cooperative            CHS                                    92
Agriculture manufacturing          John Deere                             83
Airline                            American Airlines                      91
                                   Delta Air Lines                        87
                                   United Airlines                        98
Apparel                            Nike                                   95
Automotive and energy              Tesla                                  50
Automotive industry                Ford Motor Company                     19
                                   General Motors                         21
Beverage                           PepsiCo                                46
Chemical industry                  Dow Chemical Company                   77
Conglomerate                       Berkshire Hathaway                      7
                                   General Electric                       54
                                   RTX Corporation                        59
Conglomerate and telecomunications AT&T                                   30
Consumer products manufacturing    Procter & Gamble                       51
Electronics industry               Apple                                   4
Financial                          American Express                       79
                                   Nationwide Mutual Insurance Company    85
Financial services                 JPMorgan Chase                         23
Financials                         Bank of America                        32
                                   Citigroup                              36
                                   Fannie Mae                             28
                                   Freddie Mac                            45
                                   Goldman Sachs                          56
                                   MetLife                                55
                                   Morgan Stanley                         63
                                   Prudential Financial                   69
                                   State Farm                             44
                                   StoneX Group                           61
                                   Wells Fargo                            47
Food industry                      Archer Daniels Midland                 35
                                   Bunge Limited                          58
Food processing                    Performance Food Group                 93
                                   Tyson Foods                            82
Food service                       Sysco                                  57
Health                             McKesson Corporation                    9
Health insurance                   Cigna                                  15
                                   Humana                                 42
Healthcare                         CVS Health                              6
                                   Cardinal Health                        14
                                   Centene                                25
                                   Elevance Health                        22
                                   HCA Healthcare                         68
                                   UnitedHealth Group                      5
Infotech                           TD Synnex                              66
Insurance                          AIG                                    78
                                   Allstate                               86
                                   Liberty Mutual                         88
                                   New York Life Insurance Company        73
                                   Progressive Corporation                90
Laboratory instruments             Thermo Fisher Scientific               99
Logistics                          United States Postal Service           52
Machinery                          Caterpillar                            70
Media                              The Walt Disney Company                48
Petroleum industry                 Chevron Corporation                    10
                                   ConocoPhillips                         49
                                   Energy Transfer Partners               43
                                   Enterprise Products                    74
                                   ExxonMobil                              3
                                   Marathon Petroleum                     16
                                   PBF Energy                             94
                                   Phillips 66                            17
                                   Plains All American Pipeline           76
                                   Valero Energy                          18
Petroleum industry and logistics   World Fuel Services                    72
Pharmaceutical industry            AbbVie                                 75
                                   AmerisourceBergen                      11
                                   Bristol-Myers Squibb                   97
                                   Johnson & Johnson                      40
                                   Merck & Co.                            71
                                   Pfizer                                 38
                                   Walgreens Boots Alliance               27
Retail                             Albertsons                             53
                                   Best Buy                               96
                                   Costco                                 12
                                   Kroger                                 24
                                   Lowe's                                 39
                                   Publix                                 80
                                   TJX                                    89
                                   Target Corporation                     33
                                   The Home Depot                         20
                                   Walmart                                 1
Retail and cloud computing         Amazon                                  2
Technology                         Dell Technologies                      34
                                   HP                                     65
                                   Intel                                  64
                                   Meta Platforms                         31
                                   Qualcomm                              100
Technology and cloud computing     Alphabet                                8
                                   IBM                                    67
                                   Microsoft                              13
Telecom hardware manufacturing     Cisco                                  84
Telecommunications                 Charter Communications                 81
                                   Comcast                                29
                                   Verizon Communications                 26
Transportation                     FedEx                                  41
                                   United Parcel Service                  37

                                                                       Revenue (USD millions)  \
Industry                           Name
Aerospace and defense              Boeing                                              66,608
                                   Lockheed Martin                                     65,984
Agriculture cooperative            CHS                                                 47,194
Agriculture manufacturing          John Deere                                          52,577
Airline                            American Airlines                                   48,971
                                   Delta Air Lines                                     50,582
                                   United Airlines                                     44,955
Apparel                            Nike                                                46,710
Automotive and energy              Tesla                                               81,462
Automotive industry                Ford Motor Company                                 158,057
                                   General Motors                                     156,735
Beverage                           PepsiCo                                             86,859
Chemical industry                  Dow Chemical Company                                56,902
Conglomerate                       Berkshire Hathaway                                 302,089
                                   General Electric                                    76,555
                                   RTX Corporation                                     67,074
Conglomerate and telecomunications AT&T                                               120,741
Consumer products manufacturing    Procter & Gamble                                    80,187
Electronics industry               Apple                                              394,328
Financial                          American Express                                    55,625
                                   Nationwide Mutual Insurance Company                 51,450
Financial services                 JPMorgan Chase                                     154,792
Financials                         Bank of America                                    115,053
                                   Citigroup                                          101,078
                                   Fannie Mae                                         121,596
                                   Freddie Mac                                         86,717
                                   Goldman Sachs                                       68,711
                                   MetLife                                             69,898
                                   Morgan Stanley                                      65,936
                                   Prudential Financial                                60,050
                                   State Farm                                          89,328
                                   StoneX Group                                        66,036
                                   Wells Fargo                                         82,859
Food industry                      Archer Daniels Midland                             101,556
                                   Bunge Limited                                       67,232
Food processing                    Performance Food Group                              47,194
                                   Tyson Foods                                         53,282
Food service                       Sysco                                               68,636
Health                             McKesson Corporation                               276,711
Health insurance                   Cigna                                              180,516
                                   Humana                                              92,870
Healthcare                         CVS Health                                         322,467
                                   Cardinal Health                                    181,364
                                   Centene                                            144,547
                                   Elevance Health                                    156,595
                                   HCA Healthcare                                      60,233
                                   UnitedHealth Group                                 324,162
Infotech                           TD Synnex                                           62,344
Insurance                          AIG                                                 56,437
                                   Allstate                                            51,412
                                   Liberty Mutual                                      49,956
                                   New York Life Insurance Company                     58,445
                                   Progressive Corporation                             49,611
Laboratory instruments             Thermo Fisher Scientific                            44,915
Logistics                          United States Postal Service                        78,620
Machinery                          Caterpillar                                         59,427
Media                              The Walt Disney Company                             82,722
Petroleum industry                 Chevron Corporation                                246,252
                                   ConocoPhillips                                      82,156
                                   Energy Transfer Partners                            89,876
                                   Enterprise Products                                 58,186
                                   ExxonMobil                                         413,680
                                   Marathon Petroleum                                 180,012
                                   PBF Energy                                          46,830
                                   Phillips 66                                        175,702
                                   Plains All American Pipeline                        57,342
                                   Valero Energy                                      171,189
Petroleum industry and logistics   World Fuel Services                                 59,043
Pharmaceutical industry            AbbVie                                              58,054
                                   AmerisourceBergen                                  238,587
                                   Bristol-Myers Squibb                                46,159
                                   Johnson & Johnson                                   94,943
                                   Merck & Co.                                         59,283
                                   Pfizer                                             100,330
                                   Walgreens Boots Alliance                           132,703
Retail                             Albertsons                                          77,650
                                   Best Buy                                            46,298
                                   Costco                                             226,954
                                   Kroger                                             148,258
                                   Lowe's                                              97,059
                                   Publix                                              54,942
                                   TJX                                                 49,936
                                   Target Corporation                                 109,120
                                   The Home Depot                                     157,403
                                   Walmart                                            611,289
Retail and cloud computing         Amazon                                             513,983
Technology                         Dell Technologies                                  102,301
                                   HP                                                  62,983
                                   Intel                                               63,054
                                   Meta Platforms                                     116,609
                                   Qualcomm                                            44,200
Technology and cloud computing     Alphabet                                           282,836
                                   IBM                                                 60,530
                                   Microsoft                                          198,270
Telecom hardware manufacturing     Cisco                                               51,557
Telecommunications                 Charter Communications                              54,022
                                   Comcast                                            121,427
                                   Verizon Communications                             136,835
Transportation                     FedEx                                               93,512
                                   United Parcel Service                              100,338

                                                                       Revenue growth  \
Industry                           Name
Aerospace and defense              Boeing                                        6.9%
                                   Lockheed Martin                               1.6%
Agriculture cooperative            CHS                                          24.3%
Agriculture manufacturing          John Deere                                   19.4%
Airline                            American Airlines                            63.9%
                                   Delta Air Lines                              69.2%
                                   United Airlines                              82.5%
Apparel                            Nike                                          4.9%
Automotive and energy              Tesla                                        51.4%
Automotive industry                Ford Motor Company                           15.9%
                                   General Motors                               23.4%
Beverage                           PepsiCo                                       8.7%
Chemical industry                  Dow Chemical Company                          3.5%
Conglomerate                       Berkshire Hathaway                            9.4%
                                   General Electric                              3.2%
                                   RTX Corporation                               4.2%
Conglomerate and telecomunications AT&T                                         28.5%
Consumer products manufacturing    Procter & Gamble                              5.3%
Electronics industry               Apple                                         7.8%
Financial                          American Express                             27.3%
                                   Nationwide Mutual Insurance Company           8.6%
Financial services                 JPMorgan Chase                               21.7%
Financials                         Bank of America                              22.6%
                                   Citigroup                                    26.6%
                                   Fannie Mae                                   19.7%
                                   Freddie Mac                                  31.6%
                                   Goldman Sachs                                 5.7%
                                   MetLife                                       1.7%
                                   Morgan Stanley                                7.9%

In [37]:
df2.loc['Financials','Citigroup']

Rank                                           36
Revenue (USD millions)                    101,078
Revenue growth                              26.6%
Employees                                 238,104
Headquarters              New York City, New York
Name: (Financials, Citigroup), dtype: object

In [42]:
group_by_ind= df.groupby('Industry')

In [43]:
group_by_ind.mean()

                                         Rank
Industry
Aerospace and defense               61.000000
Agriculture cooperative             92.000000
Agriculture manufacturing           83.000000
Airline                             92.000000
Apparel                             95.000000
Automotive and energy               50.000000
Automotive industry                 20.000000
Beverage                            46.000000
Chemical industry                   77.000000
Conglomerate                        40.000000
Conglomerate and telecomunications  30.000000
Consumer products manufacturing     51.000000
Electronics industry                 4.000000
Financial                           82.000000
Financial services                  23.000000
Financials                          48.727273
Food industry                       46.500000
Food processing                     87.500000
Food service                        57.000000
Health                               9.000000
Health insurance                    28.500000
Healthcare                          23.333333
Infotech                            66.000000
Insurance                           83.000000
Laboratory instruments              99.000000
Logistics                           52.000000
Machinery                           70.000000
Media                               48.000000
Petroleum industry                  40.000000
Petroleum industry and logistics    72.000000
Pharmaceutical industry             51.285714
Retail                              44.700000
Retail and cloud computing           2.000000
Technology                          58.800000
Technology and cloud computing      29.333333
Telecom hardware manufacturing      84.000000
Telecommunications                  45.333333
Transportation                      39.000000

In [44]:
group_by_ind.count()

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Aerospace and defense,2,2,2,2,2,2
Agriculture cooperative,1,1,1,1,1,1
Agriculture manufacturing,1,1,1,1,1,1
Airline,3,3,3,3,3,3
Apparel,1,1,1,1,1,1
Automotive and energy,1,1,1,1,1,1
Automotive industry,2,2,2,2,2,2
Beverage,1,1,1,1,1,1
Chemical industry,1,1,1,1,1,1
Conglomerate,3,3,3,3,3,3
Conglomerate and telecomunications,1,1,1,1,1,1
Consumer products manufacturing,1,1,1,1,1,1
Electronics industry,1,1,1,1,1,1
Financial,2,2,2,2,2,2
Financial services,1,1,1,1,1,1
Financials,11,11,11,11,11,11
Food industry,2,2,2,2,2,2
Food processing,2,2,2,2,2,2
Food service,1,1,1,1,1,1
Health,1,1,1,1,1,1
Health insurance,2,2,2,2,2,2
Healthcare,6,6,6,6,6,6
Infotech,1,1,1,1,1,1
Insurance,5,5,5,5,5,5
Laboratory instruments,1,1,1,1,1,1
Logistics,1,1,1,1,1,1
Machinery,1,1,1,1,1,1
Media,1,1,1,1,1,1
Petroleum industry,10,10,10,10,10,10
Petroleum industry and logistics,1,1,1,1,1,1
Pharmaceutical industry,7,7,7,7,7,7
Retail,10,10,10,10,10,10
Retail and cloud computing,1,1,1,1,1,1
Technology,5,5,5,5,5,5
Technology and cloud computing,3,3,3,3,3,3
Telecom hardware manufacturing,1,1,1,1,1,1
Telecommunications,3,3,3,3,3,3
Transportation,2,2,2,2,2,2

In [46]:
group_by_ind.max()

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Aerospace and defense,62,Lockheed Martin,"66,608",6.9%,"156,000","Bethesda, Maryland"
Agriculture cooperative,92,CHS,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Agriculture manufacturing,83,John Deere,"52,577",19.4%,"82,239","Moline, Illinois"
Airline,98,United Airlines,"50,582",82.5%,"95,000","Fort Worth, Texas"
Apparel,95,Nike,"46,710",4.9%,"79,100","Beaverton, Oregon"
Automotive and energy,50,Tesla,"81,462",51.4%,"127,855","Austin, Texas"
Automotive industry,21,General Motors,"158,057",23.4%,"173,000","Detroit, Michigan"
Beverage,46,PepsiCo,"86,859",8.7%,"315,000","Purchase, New York"
Chemical industry,77,Dow Chemical Company,"56,902",3.5%,"37,800","Midland, Michigan"
Conglomerate,59,RTX Corporation,"76,555",9.4%,"383,000","Omaha, Nebraska"
Conglomerate and telecomunications,30,AT&T,"120,741",28.5%,"160,700","Dallas, Texas"
Consumer products manufacturing,51,Procter & Gamble,"80,187",5.3%,"106,000","Cincinnati, Ohio"
Electronics industry,4,Apple,"394,328",7.8%,"164,000","Cupertino, California"
Financial,85,Nationwide Mutual Insurance Company,"55,625",8.6%,"77,300","New York City, New York"
Financial services,23,JPMorgan Chase,"154,792",21.7%,"293,723","New York City, New York"
Financials,69,Wells Fargo,"89,328",8.6%,"82,427","Washington, D.C."
Food industry,58,Bunge Limited,"67,232",19.1%,"41,181","White Plains, New York"
Food processing,93,Tyson Foods,"53,282",61.6%,"34,825","Springdale, Arkansas"
Food service,57,Sysco,"68,636",33.8%,"70,510","Houston, Texas"
Health,9,McKesson Corporation,"276,711",4.8%,"48,500","Irving, Texas"
Health insurance,42,Humana,"92,870",3.7%,"70,231","Louisville, Kentucky"
Healthcare,68,UnitedHealth Group,"60,233",2.5%,"74,300","Woonsocket, Rhode Island"
Infotech,66,TD Synnex,"62,344",97.2%,"28,500","Clearwater, Florida"
Insurance,90,Progressive Corporation,"58,445",8.4%,"55,063","Northfield Township, Cook County, Illinois"
Laboratory instruments,99,Thermo Fisher Scientific,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Logistics,52,United States Postal Service,"78,620",2.0%,"576,000","Washington, D.C."
Machinery,70,Caterpillar,"59,427",16.6%,"109,100","Deerfield, Illinois"
Media,48,The Walt Disney Company,"82,722",22.7%,"195,800","Burbank, California"
Petroleum industry,94,Valero Energy,"89,876",71.8%,"9,743","Spring, Texas"
Petroleum industry and logistics,72,World Fuel Services,"59,043",88.4%,"5,214","Miami, Florida"
Pharmaceutical industry,97,Walgreens Boots Alliance,"94,943",3.3%,"83,000","New York City, New York"
Retail,96,Walmart,"97,059",8.0%,"71,100","Richfield, Minnesota"
Retail and cloud computing,2,Amazon,"513,983",9.4%,"1,540,000","Seattle, Washington"
Technology,100,Qualcomm,"63,054",4.4%,"86,482","Santa Clara, California"
Technology and cloud computing,67,Microsoft,"60,530",9.8%,"303,100","Redmond, Washington"
Telecom hardware manufacturing,84,Cisco,"51,557",3.5%,"83,300","San Jose, California"
Telecommunications,81,Verizon Communications,"54,022",4.5%,"186,000","Stamford, Connecticut"
Transportation,41,United Parcel Service,"93,512",3.1%,"518,249","Memphis, Tennessee"

In [56]:
df['Revenue (USD millions)'] = original_df['Revenue (USD millions)'].copy()

df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,ExxonMobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology and cloud computing,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,AmerisourceBergen,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology and cloud computing,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive industry,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate and telecomunications,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Arlington County, Virginia"
60,61,StoneX Group,Financials,"66,036",55.3%,305,"New York City, New York"
61,62,Lockheed Martin,Aerospace and defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology and cloud computing,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom hardware manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [57]:
df['Revenue (USD millions)'] = df['Revenue (USD millions)'].str.replace(',','').astype(int)

In [58]:
group_by_ind.agg({'Revenue (USD millions)':['mean','max','count','sum']})

                                   Revenue (USD millions)                \
                                                     mean     max count
Industry
Aerospace and defense                        66296.000000   66608     2
Agriculture cooperative                      47194.000000   47194     1
Agriculture manufacturing                    52577.000000   52577     1
Airline                                      48169.333333   50582     3
Apparel                                      46710.000000   46710     1
Automotive and energy                        81462.000000   81462     1
Automotive industry                         157396.000000  158057     2
Beverage                                     86859.000000   86859     1
Chemical industry                            56902.000000   56902     1
Conglomerate                                148572.666667  302089     3
Conglomerate and telecomunications          120741.000000  120741     1
Consumer products manufacturing              80187.000000   80187     1
Electronics industry                        394328.000000  394328     1
Financial                                    53537.500000   55625     2
Financial services                          154792.000000  154792     1
Financials                                   84296.545455  121596    11
Food industry                                84394.000000  101556     2
Food processing                              50238.000000   53282     2
Food service                                 68636.000000   68636     1
Health                                      276711.000000  276711     1
Health insurance                            136693.000000  180516     2
Healthcare                                  198228.000000  324162     6
Infotech                                     62344.000000   62344     1
Insurance                                    53172.200000   58445     5
Laboratory instruments                       44915.000000   44915     1
Logistics                                    78620.000000   78620     1
Machinery                                    59427.000000   59427     1
Media                                        82722.000000   82722     1
Petroleum industry                          152122.500000  413680    10
Petroleum industry and logistics             59043.000000   59043     1
Pharmaceutical industry                     104294.142857  238587     7
Retail                                      157890.900000  611289    10
Retail and cloud computing                  513983.000000  513983     1
Technology                                   77829.400000  116609     5
Technology and cloud computing              180545.333333  282836     3
Telecom hardware manufacturing               51557.000000   51557     1
Telecommunications                          104094.666667  136835     3
Transportation                               96925.000000  100338     2


                                        sum
Industry
Aerospace and defense                132592
Agriculture cooperative               47194
Agriculture manufacturing             52577
Airline                              144508
Apparel                               46710
Automotive and energy                 81462
Automotive industry                  314792
Beverage                              86859
Chemical industry                     56902
Conglomerate                         445718
Conglomerate and telecomunications   120741
Consumer products manufacturing       80187
Electronics industry                 394328
Financial                            107075
Financial services                   154792
Financials                           927262
Food industry                        168788
Food processing                      100476
Food service                          68636
Health                               276711
Health insurance                     273386
Healthcare                          1189368
Infotech                              62344
Insurance                            265861
Laboratory instruments                44915
Logistics                             78620
Machinery                             59427
Media                                 82722
Petroleum industry                  1521225
Petroleum industry and logistics      59043
Pharmaceutical industry              730059
Retail                              1578909
Retail and cloud computing           513983
Technology                           389147
Technology and cloud computing       541636
Telecom hardware manufacturing        51557
Telecommunications                   312284
Transportation                       193850

In [59]:
df.groupby('Name').describe()

                                     Rank                                  \
                                    count   mean std    min    25%    50%
Name
AIG                                   1.0   78.0 NaN   78.0   78.0   78.0
AT&T                                  1.0   30.0 NaN   30.0   30.0   30.0
AbbVie                                1.0   75.0 NaN   75.0   75.0   75.0
Albertsons                            1.0   53.0 NaN   53.0   53.0   53.0
Allstate                              1.0   86.0 NaN   86.0   86.0   86.0
Alphabet                              1.0    8.0 NaN    8.0    8.0    8.0
Amazon                                1.0    2.0 NaN    2.0    2.0    2.0
American Airlines                     1.0   91.0 NaN   91.0   91.0   91.0
American Express                      1.0   79.0 NaN   79.0   79.0   79.0
AmerisourceBergen                     1.0   11.0 NaN   11.0   11.0   11.0
Apple                                 1.0    4.0 NaN    4.0    4.0    4.0
Archer Daniels Midland                1.0   35.0 NaN   35.0   35.0   35.0
Bank of America                       1.0   32.0 NaN   32.0   32.0   32.0
Berkshire Hathaway                    1.0    7.0 NaN    7.0    7.0    7.0
Best Buy                              1.0   96.0 NaN   96.0   96.0   96.0
Boeing                                1.0   60.0 NaN   60.0   60.0   60.0
Bristol-Myers Squibb                  1.0   97.0 NaN   97.0   97.0   97.0
Bunge Limited                         1.0   58.0 NaN   58.0   58.0   58.0
CHS                                   1.0   92.0 NaN   92.0   92.0   92.0
CVS Health                            1.0    6.0 NaN    6.0    6.0    6.0
Cardinal Health                       1.0   14.0 NaN   14.0   14.0   14.0
Caterpillar                           1.0   70.0 NaN   70.0   70.0   70.0
Centene                               1.0   25.0 NaN   25.0   25.0   25.0
Charter Communications                1.0   81.0 NaN   81.0   81.0   81.0
Chevron Corporation                   1.0   10.0 NaN   10.0   10.0   10.0
Cigna                                 1.0   15.0 NaN   15.0   15.0   15.0
Cisco                                 1.0   84.0 NaN   84.0   84.0   84.0
Citigroup                             1.0   36.0 NaN   36.0   36.0   36.0
Comcast                               1.0   29.0 NaN   29.0   29.0   29.0
ConocoPhillips                        1.0   49.0 NaN   49.0   49.0   49.0
Costco                                1.0   12.0 NaN   12.0   12.0   12.0
Dell Technologies                     1.0   34.0 NaN   34.0   34.0   34.0
Delta Air Lines                       1.0   87.0 NaN   87.0   87.0   87.0
Dow Chemical Company                  1.0   77.0 NaN   77.0   77.0   77.0
Elevance Health                       1.0   22.0 NaN   22.0   22.0   22.0
Energy Transfer Partners              1.0   43.0 NaN   43.0   43.0   43.0
Enterprise Products                   1.0   74.0 NaN   74.0   74.0   74.0
ExxonMobil                            1.0    3.0 NaN    3.0    3.0    3.0
Fannie Mae                            1.0   28.0 NaN   28.0   28.0   28.0
FedEx                                 1.0   41.0 NaN   41.0   41.0   41.0
Ford Motor Company                    1.0   19.0 NaN   19.0   19.0   19.0
Freddie Mac                           1.0   45.0 NaN   45.0   45.0   45.0
General Electric                      1.0   54.0 NaN   54.0   54.0   54.0
General Motors                        1.0   21.0 NaN   21.0   21.0   21.0
Goldman Sachs                         1.0   56.0 NaN   56.0   56.0   56.0
HCA Healthcare                        1.0   68.0 NaN   68.0   68.0   68.0
HP                                    1.0   65.0 NaN   65.0   65.0   65.0
Humana                                1.0   42.0 NaN   42.0   42.0   42.0
IBM                                   1.0   67.0 NaN   67.0   67.0   67.0
Intel                                 1.0   64.0 NaN   64.0   64.0   64.0
JPMorgan Chase                        1.0   23.0 NaN   23.0   23.0   23.0
John Deere                            1.0   83.0 NaN   83.0   83.0   83.0
Johnson & Johnson                     1.0   40.0 NaN   40.0   40.0   40.0
Kroger                                1.0   24.0 NaN   24.0   24.0   24.0
Liberty Mutual                        1.0   88.0 NaN   88.0   88.0   88.0
Lockheed Martin                       1.0   62.0 NaN   62.0   62.0   62.0
Lowe's                                1.0   39.0 NaN   39.0   39.0   39.0
Marathon Petroleum                    1.0   16.0 NaN   16.0   16.0   16.0
McKesson Corporation                  1.0    9.0 NaN    9.0    9.0    9.0
Merck & Co.                           1.0   71.0 NaN   71.0   71.0   71.0
MetLife                               1.0   55.0 NaN   55.0   55.0   55.0
Meta Platforms                        1.0   31.0 NaN   31.0   31.0   31.0
Microsoft                             1.0   13.0 NaN   13.0   13.0   13.0
Morgan Stanley                        1.0   63.0 NaN   63.0   63.0   63.0
Nationwide Mutual Insurance Company   1.0   85.0 NaN   85.0   85.0   85.0
New York Life Insurance Company       1.0   73.0 NaN   73.0   73.0   73.0
Nike                                  1.0   95.0 NaN   95.0   95.0   95.0
PBF Energy                            1.0   94.0 NaN   94.0   94.0   94.0
PepsiCo                               1.0   46.0 NaN   46.0   46.0   46.0
Performance Food Group                1.0   93.0 NaN   93.0   93.0   93.0
Pfizer                                1.0   38.0 NaN   38.0   38.0   38.0
Phillips 66                           1.0   17.0 NaN   17.0   17.0   17.0
Plains All American Pipeline          1.0   76.0 NaN   76.0   76.0   76.0
Procter & Gamble                      1.0   51.0 NaN   51.0   51.0   51.0
Progressive Corporation               1.0   90.0 NaN   90.0   90.0   90.0
Prudential Financial                  1.0   69.0 NaN   69.0   69.0   69.0
Publix                                1.0   80.0 NaN   80.0   80.0   80.0
Qualcomm                              1.0  100.0 NaN  100.0  100.0  100.0
RTX Corporation                       1.0   59.0 NaN   59.0   59.0   59.0
State Farm                            1.0   44.0 NaN   44.0   44.0   44.0
StoneX Group                          1.0   61.0 NaN   61.0   61.0   61.0
Sysco                                 1.0   57.0 NaN   57.0   57.0   57.0
TD Synnex                             1.0   66.0 NaN   66.0   66.0   66.0
TJX                                   1.0   89.0 NaN   89.0   89.0   89.0
Target Corporation                    1.0   33.0 NaN   33.0   33.0   33.0
Tesla                                 1.0   50.0 NaN   50.0   50.0   50.0
The Home Depot                        1.0   20.0 NaN   20.0   20.0   20.0
The Walt Disney Company               1.0   48.0 NaN   48.0   48.0   48.0
Thermo Fisher Scientific              1.0   99.0 NaN   99.0   99.0   99.0
Tyson Foods                           1.0   82.0 NaN   82.0   82.0   82.0
United Airlines                       1.0   98.0 NaN   98.0   98.0   98.0
United Parcel Service                 1.0   37.0 NaN   37.0   37.0   37.0
United States Postal Service          1.0   52.0 NaN   52.0   52.0   52.0
UnitedHealth Group                    1.0    5.0 NaN    5.0    5.0    5.0
Valero Energy                         1.0   18.0 NaN   18.0   18.0   18.0
Verizon Communications                1.0   26.0 NaN   26.0   26.0   26.0
Walgreens Boots Alliance              1.0   27.0 NaN   27.0   27.0   27.0
Walmart                               1.0    1.0 NaN    1.0    1.0    1.0
Wells Fargo                           1.0   47.0 NaN   47.0   47.0   47.0
World Fuel Services                   1.0   72.0 NaN   72.0   72.0   72.0

                                                  Revenue (USD millions)  \
                                       75%    max                  count
Name
AIG                                   78.0   78.0                    1.0
AT&T                                  30.0   30.0                    1.0
AbbVie                                75.0   75.0                    1.0
Albertsons                            53.0   53.0                    1.0
Allstate                              86.0   86.0                    1.0
Alphabet                               8.0    8.0                    1.0
Amazon                                 2.0    2.0                    1.0
American Airlines                     91.0   91.0                    1.0
American Express                      79.0   79.0                    1.0
AmerisourceBergen                     11.0   11.0                    1.0
Apple                                  4.0    4.0                    1.0
Archer Daniels Midland                35.0   35.0                    1.0
Bank of America                       32.0   32.0                    1.0
Berkshire Hathaway                     7.0    7.0                    1.0
Best Buy                              96.0   96.0                    1.0
Boeing                                60.0   60.0                    1.0
Bristol-Myers Squibb                  97.0   97.0                    1.0
Bunge Limited                         58.0   58.0                    1.0
CHS                                   92.0   92.0                    1.0
CVS Health                             6.0    6.0                    1.0
Cardinal Health                       14.0   14.0                    1.0
Caterpillar                           70.0   70.0                    1.0
Centene                               25.0   25.0                    1.0
Charter Communications                81.0   81.0                    1.0
Chevron Corporation                   10.0   10.0                    1.0
Cigna                                 15.0   15.0                    1.0
Cisco                                 84.0   84.0                    1.0
Citigroup                             36.0   36.0                    1.0
Comcast                               29.0   29.0                    1.0
ConocoPhillips                        49.0   49.0                    1.0
Costco                                12.0   12.0                    1.0
Dell Technologies                     34.0   34.0                    1.0
Delta Air Lines                       87.0   87.0                    1.0
Dow Chemical Company                  77.0   77.0                    1.0
Elevance Health                       22.0   22.0                    1.0
Energy Transfer Partners              43.0   43.0                    1.0
Enterprise Products                   74.0   74.0                    1.0
ExxonMobil                             3.0    3.0                    1.0
Fannie Mae                            28.0   28.0                    1.0
FedEx                                 41.0   41.0                    1.0
Ford Motor Company                    19.0   19.0                    1.0
Freddie Mac                           45.0   45.0                    1.0
General Electric                      54.0   54.0                    1.0
General Motors                        21.0   21.0                    1.0
Goldman Sachs                         56.0   56.0                    1.0
HCA Healthcare                        68.0   68.0                    1.0
HP                                    65.0   65.0                    1.0
Humana                                42.0   42.0                    1.0
IBM                                   67.0   67.0                    1.0
Intel                                 64.0   64.0                    1.0
JPMorgan Chase                        23.0   23.0                    1.0
John Deere                            83.0   83.0                    1.0
Johnson & Johnson                     40.0   40.0                    1.0
Kroger                                24.0   24.0                    1.0
Liberty Mutual                        88.0   88.0                    1.0
Lockheed Martin                       62.0   62.0                    1.0
Lowe's                                39.0   39.0                    1.0
Marathon Petroleum                    16.0   16.0                    1.0
McKesson Corporation                   9.0    9.0                    1.0
Merck & Co.                           71.0   71.0                    1.0
MetLife                               55.0   55.0                    1.0
Meta Platforms                        31.0   31.0                    1.0
Microsoft                             13.0   13.0                    1.0
Morgan Stanley                        63.0   63.0                    1.0
Nationwide Mutual Insurance Company   85.0   85.0                    1.0
New York Life Insurance Company       73.0   73.0                    1.0
Nike                                  95.0   95.0                    1.0
PBF Energy                            94.0   94.0                    1.0
PepsiCo                               46.0   46.0                    1.0
Performance Food Group                93.0   93.0                    1.0
Pfizer                                38.0   38.0                    1.0
Phillips 66                           17.0   17.0                    1.0
Plains All American Pipeline          76.0   76.0                    1.0
Procter & Gamble                      51.0   51.0                    1.0
Progressive Corporation               90.0   90.0                    1.0
Prudential Financial                  69.0   69.0                    1.0
Publix                                80.0   80.0                    1.0
Qualcomm                             100.0  100.0                    1.0
RTX Corporation                       59.0   59.0                    1.0
State Farm                            44.0   44.0                    1.0
StoneX Group                          61.0   61.0                    1.0
Sysco                                 57.0   57.0                    1.0
TD Synnex                             66.0   66.0                    1.0
TJX                                   89.0   89.0                    1.0
Target Corporation                    33.0   33.0                    1.0
Tesla                                 50.0   50.0                    1.0
The Home Depot                        20.0   20.0                    1.0
The Walt Disney Company               48.0   48.0                    1.0
Thermo Fisher Scientific              99.0   99.0                    1.0
Tyson Foods                           82.0   82.0                    1.0
United Airlines                       98.0   98.0                    1.0
United Parcel Service                 37.0   37.0                    1.0
United States Postal Service          52.0   52.0                    1.0
UnitedHealth Group                     5.0    5.0                    1.0
Valero Energy                         18.0   18.0                    1.0
Verizon Communications                26.0   26.0                    1.0
Walgreens Boots Alliance              27.0   27.0                    1.0
Walmart                                1.0    1.0                    1.0
Wells Fargo                           47.0   47.0                    1.0
World Fuel Services                   72.0   72.0                    1.0

                                                                       \
                                         mean std       min       25%
Name
AIG                                   56437.0 NaN   56437.0   56437.0
AT&T                                 120741.0 NaN  120741.0  120741.0
AbbVie                                58054.0 NaN   58054.0   58054.0
Albertsons                            77650.0 NaN   77650.0   77650.0
Allstate                              51412.0 NaN   51412.0   51412.0
Alphabet                             282836.0 NaN  282836.0  282836.0
Amazon                               513983.0 NaN  513983.0  513983.0
American Airlines                     48971.0 NaN   48971.0   48971.0
American Express                      55625.0 NaN   55625.0   55625.0
AmerisourceBergen                    238587.0 NaN  238587.0  238587.0
Apple                                394328.0 NaN  394328.0  394328.0
Archer Daniels Midland               101556.0 NaN  101556.0  101556.0
Bank of America                      115053.0 NaN  115053.0  115053.0
Berkshire Hathaway                   302089.0 NaN  302089.0  302089.0
Best Buy                              46298.0 NaN   46298.0   46298.0
Boeing                                66608.0 NaN   66608.0   66608.0
Bristol-Myers Squibb                  46159.0 NaN   46159.0   46159.0
Bunge Limited                         67232.0 NaN   67232.0   67232.0
CHS                                   47194.0 NaN   47194.0   47194.0
CVS Health                           322467.0 NaN  322467.0  322467.0
Cardinal Health                      181364.0 NaN  181364.0  181364.0
Caterpillar                           59427.0 NaN   59427.0   59427.0
Centene                              144547.0 NaN  144547.0  144547.0
Charter Communications                54022.0 NaN   54022.0   54022.0
Chevron Corporation                  246252.0 NaN  246252.0  246252.0
Cigna                                180516.0 NaN  180516.0  180516.0
Cisco                                 51557.0 NaN   51557.0   51557.0
Citigroup                            101078.0 NaN  101078.0  101078.0
Comcast                              121427.0 NaN  121427.0  121427.0
ConocoPhillips                        82156.0 NaN   82156.0   82156.0
Costco                               226954.0 NaN  226954.0  226954.0
Dell Technologies                    102301.0 NaN  102301.0  102301.0
Delta Air Lines                       50582.0 NaN   50582.0   50582.0
Dow Chemical Company                  56902.0 NaN   56902.0   56902.0
Elevance Health                      156595.0 NaN  156595.0  156595.0
Energy Transfer Partners              89876.0 NaN   89876.0   89876.0
Enterprise Products                   58186.0 NaN   58186.0   58186.0
ExxonMobil                           413680.0 NaN  413680.0  413680.0
Fannie Mae                           121596.0 NaN  121596.0  121596.0
FedEx                                 93512.0 NaN   93512.0   93512.0
Ford Motor Company                   158057.0 NaN  158057.0  158057.0
Freddie Mac                           86717.0 NaN   86717.0   86717.0
General Electric                      76555.0 NaN   76555.0   76555.0
General Motors                       156735.0 NaN  156735.0  156735.0
Goldman Sachs                         68711.0 NaN   68711.0   68711.0
HCA Healthcare                        60233.0 NaN   60233.0   60233.0
HP                                    62983.0 NaN   62983.0   62983.0
Humana                                92870.0 NaN   92870.0   92870.0
IBM                                   60530.0 NaN   60530.0   60530.0
Intel                                 63054.0 NaN   63054.0   63054.0
JPMorgan Chase                       154792.0 NaN  154792.0  154792.0
John Deere                            52577.0 NaN   52577.0   52577.0
Johnson & Johnson                     94943.0 NaN   94943.0   94943.0
Kroger                               148258.0 NaN  148258.0  148258.0
Liberty Mutual                        49956.0 NaN   49956.0   49956.0
Lockheed Martin                       65984.0 NaN   65984.0   65984.0
Lowe's                                97059.0 NaN   97059.0   97059.0
Marathon Petroleum                   180012.0 NaN  180012.0  180012.0
McKesson Corporation                 276711.0 NaN  276711.0  276711.0
Merck & Co.                           59283.0 NaN   59283.0   59283.0
MetLife                               69898.0 NaN   69898.0   69898.0
Meta Platforms                       116609.0 NaN  116609.0  116609.0
Microsoft                            198270.0 NaN  198270.0  198270.0
Morgan Stanley                        65936.0 NaN   65936.0   65936.0
Nationwide Mutual Insurance Company   51450.0 NaN   51450.0   51450.0
New York Life Insurance Company       58445.0 NaN   58445.0   58445.0
Nike                                  46710.0 NaN   46710.0   46710.0
PBF Energy                            46830.0 NaN   46830.0   46830.0
PepsiCo                               86859.0 NaN   86859.0   86859.0